#include <stdio.h>

const double MEGAWATTS = 1e6;
const double WATER_MASS = 1000.0;
const double GRAVITY = 9.81;
const double EFFICIENCY = 0.9;

double calculate_power (double height, double flow_rate) {
    double potential_energy = GRAVITY * height * WATER_MASS * flow_rate;
    double power = potential_energy * EFFICIENCY;
    return power/MEGAWATTS;
}

int main () {
    printf("Enter the height of the dam in meters: ");
    double height;
    scanf("%lf", &height);

    printf("Enter the flow rate in cubic meters per second: ");
    double flow_rate;
    scanf("%lf", &flow_rate);

    double power = calculate_power(height, flow_rate);

    printf("The power generated by the dam: %.2f MW\n", power);

    return 0;
}